# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/KandyIO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/KandyIO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/KandyIO/CMakeFiles /home/pi/KandyIO/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/KandyIO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KandyClient

# Build rule for target.
KandyClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KandyClient
.PHONY : KandyClient

# fast build rule for target.
KandyClient/fast:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/build
.PHONY : KandyClient/fast

httpClient.o: httpClient.cpp.o

.PHONY : httpClient.o

# target to build an object file
httpClient.cpp.o:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/httpClient.cpp.o
.PHONY : httpClient.cpp.o

httpClient.i: httpClient.cpp.i

.PHONY : httpClient.i

# target to preprocess a source file
httpClient.cpp.i:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/httpClient.cpp.i
.PHONY : httpClient.cpp.i

httpClient.s: httpClient.cpp.s

.PHONY : httpClient.s

# target to generate assembly for a file
httpClient.cpp.s:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/httpClient.cpp.s
.PHONY : httpClient.cpp.s

kandyClient.o: kandyClient.cpp.o

.PHONY : kandyClient.o

# target to build an object file
kandyClient.cpp.o:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/kandyClient.cpp.o
.PHONY : kandyClient.cpp.o

kandyClient.i: kandyClient.cpp.i

.PHONY : kandyClient.i

# target to preprocess a source file
kandyClient.cpp.i:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/kandyClient.cpp.i
.PHONY : kandyClient.cpp.i

kandyClient.s: kandyClient.cpp.s

.PHONY : kandyClient.s

# target to generate assembly for a file
kandyClient.cpp.s:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/kandyClient.cpp.s
.PHONY : kandyClient.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/KandyClient.dir/build.make CMakeFiles/KandyClient.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... KandyClient"
	@echo "... httpClient.o"
	@echo "... httpClient.i"
	@echo "... httpClient.s"
	@echo "... kandyClient.o"
	@echo "... kandyClient.i"
	@echo "... kandyClient.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

